services:
  ollama:
    volumes:
      - 'ollama_models:/root/.ollama/models'
      - 'whisper_models:/data/cache/whisper/models'
    ports:
      - '11434:11434'
    environment:
      OLLAMA_ORIGINS: '*'
      ENABLE_OLLAMA_API: 'True'
      DATA_DIR: '/data'
    container_name: ollama
    image: ollama/ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: always

volumes:
  ollama_models:
  whisper_models:
